//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizTalkComponents.PipelineComponents.CustomJsonCoders.Tests.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizTalkComponents.PipelineComponents.CustomJsonCoders.Tests.UnitTests.Properties." +
                            "Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Events&gt;
        ///  &lt;Event&gt;
        ///    &lt;Field1&gt;Field1_0&lt;/Field1&gt;
        ///    &lt;Field2&gt;Field2_0&lt;/Field2&gt;
        ///  &lt;/Event&gt;
        ///  &lt;Event&gt;
        ///    &lt;Field1&gt;Field1_0&lt;/Field1&gt;
        ///    &lt;Field2&gt;Field2_0&lt;/Field2&gt;
        ///  &lt;/Event&gt;
        ///  &lt;Event&gt;
        ///    &lt;Field1&gt;Field1_0&lt;/Field1&gt;
        ///    &lt;Field2&gt;Field2_0&lt;/Field2&gt;
        ///  &lt;/Event&gt;
        ///&lt;/Events&gt;.
        /// </summary>
        internal static string ArrayOfEvents {
            get {
                return ResourceManager.GetString("ArrayOfEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Events&gt;
        ///  &lt;Event&gt;
        ///    &lt;Field1&gt;Field1_0&lt;/Field1&gt;
        ///    &lt;Field2&gt;Field2_0&lt;/Field2&gt;
        ///  &lt;/Event&gt;
        ///  &lt;Event&gt;
        ///    &lt;Field1&gt;Field1_0&lt;/Field1&gt;
        ///    &lt;Field2&gt;Field2_0&lt;/Field2&gt;
        ///  &lt;/Event&gt;
        ///  &lt;Event2&gt;
        ///    &lt;Field1&gt;Field1_0&lt;/Field1&gt;
        ///    &lt;Field2&gt;Field2_0&lt;/Field2&gt;
        ///  &lt;/Event2&gt;
        ///&lt;/Events&gt;.
        /// </summary>
        internal static string DifferentEvents {
            get {
                return ResourceManager.GetString("DifferentEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Events&gt;
        ///&lt;/Events&gt;.
        /// </summary>
        internal static string EmptyEvents {
            get {
                return ResourceManager.GetString("EmptyEvents", resourceCulture);
            }
        }
    }
}
